config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :user_applications do
    member do
      patch :update_status
      post :email_applicant
    end
  end

  # Defines the root path route ("/")
  root 'user_applications#index'
end

app/controllers/admin_view_controller.rb
class AdminViewController < ApplicationController
  def admin_view
    @applicants = Applicant.order(params[:sort])
  end

  def update
    @applicant = Applicant.find(params[:id])
    if params[:status].present? then
      @applicant.update(status: params[:status])
    end
    redirect_to admin_path, notice: "Status for #{@applicant.full_name} updated to #{@applicant.status}"
  end

  def delete
    applicant = Applicant.find_by_email(params[:email])
    applicant.destroy
  end

  def email
    @applicant = Applicant.find(params[:format])
    redirect_to admin_path, notice: "Sent email to #{@applicant.full_name}, regarding their status update to #{@applicant.status}"
    AdminMailer.with(applicant: @applicant).post_created.deliver_later
  end
end

app/helpers/admin_view_helper.rb
module AdminViewHelper
end

app/views/admin_view/admin_view.html.erb
<section class="container px-4 mx-auto">
    <div class="flex flex-col">
        <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
                <div class="overflow-hidden border border-gray-200 dark:border-gray-700 md:rounded-lg">
                    <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                        <thead class="bg-gray-50 dark:bg-blue-950">
                            <tr>
                                <th scope="col" class="py-3.5 px-4 text-sm font-bold text-left rtl:text-right text-blue-200 hover:text-white">
                                    <div class="flex items-center gap-x-3">
                                        <%= link_to "Submission ID", :sort => "id" %>
                                    </div>
                                </th>
                                <th scope="col" class="px-4 py-3.5 text-sm font-bold text-left rtl:text-right text-blue-200 hover:text-white">
                                    <%= link_to "Date", :sort => "created_at" %>
                                </th>

                                <th scope="col" class="px-4 py-3.5 text-sm font-bold text-left rtl:text-right text-blue-200 hover:text-white">
                                    <%= link_to "Applicant", :sort => "full_name" %>
                                </th>

                                <th scope="col" class="px-4 py-3.5 text-sm font-bold text-left rtl:text-right text-blue-200 hover:text-white">
                                    <%= link_to "Found Through", :sort => "how_find" %>
                                </th>

                                <th scope="col" class="px-4 py-3.5 text-sm font-bold text-left rtl:text-right text-blue-200">
                                   Skills
                                </th>

                                <th scope="col" class="px-4 py-3.5 text-sm font-bold text-left rtl:text-right text-blue-200 hover:text-white">
                                    <%= link_to "Status", :sort => "status" %>
                                </th>
                            </tr>
                        </thead>
                        <tbody class="bg-white divide-y divide-gray-200 dark:divide-gray-700 dark:bg-gray-900">
                          <% @applicants.all.each do |applicant| %>
                              <tr>
                                  <td class="px-4 py-4 text-sm font-medium text-gray-700 dark:text-gray-200 whitespace-nowrap">
                                      <div class="inline-flex items-center gap-x-3">
                                          <span><%= applicant.id %></span>
                                      </div>
                                  </td>
                                  <td class="px-4 py-4 text-sm text-gray-500 dark:text-gray-300 whitespace-nowrap"><%= applicant.created_at %></td>
                                  

                                  <td class="px-4 py-4 text-sm text-gray-500 dark:text-gray-300 whitespace-nowrap">
                                      <div class="flex items-center gap-x-2">
                                          <div>
                                              <h2 class="text-sm font-medium text-gray-800 dark:text-white "><%= applicant.full_name %></h2>
                                              <p class="text-xs font-normal text-gray-600 dark:text-gray-400"><%= applicant.email %></p>
                                          </div>
                                      </div>
                                  </td>
                                  <td class="px-4 py-4 text-sm text-gray-500 dark:text-gray-300 whitespace-nowrap"><%= applicant.how_find %></td>
                                  <td class="px-4 py-4 text-sm text-gray-500 dark:text-gray-300 whitespace-nowrap">
                                      <div class="flex items-center gap-x-2">
                                          <div>
                                              <p class="text-xs font-normal text-gray-600 dark:text-gray-400"><%= applicant.knows_ruby ? "Ruby" : '' %></p>
                                              <p class="text-xs font-normal text-gray-600 dark:text-gray-400"><%= applicant.knows_rails ? "Rails" : '' %></p>
                                              <p class="text-xs font-normal text-gray-600 dark:text-gray-400"><%= applicant.knows_mvc ? "MVC" : '' %></p>
                                          </div>
                                      </div>
                                  </td>
                                  <td class="px-4 py-4 text-sm font-medium text-gray-700 whitespace-nowrap">
                                    <div class="flex items-center">
                                      <%= form_with model: @new_status, url: update_path, data: {turbo: false}, method: "patch" do |form| %>
                                        <%= form.select :status, ["Application Pending","Reviewed","Not Moving Forward","Requesting Interview","Hired"], :selected => applicant.status %>
                                        <%= form.hidden_field :id, value: applicant.id %>
                                        <div class="inline-block content-center px-5">
                                             <%= form.button "Update", type: "submit", class: "shadow bg-blue-600 hover:bg-blue-500 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded"%>
                                        </div>
                                      <% end %>
                                        <div class="content-center">
                                            <%= button_to "Email", email_path(applicant.id), class: "shadow bg-blue-600 hover:bg-blue-500 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded", method: :post %>
                                        </div>
                                    </div>
                                    
                                  </td>
                              </tr>
                          <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>